### ISSUE TITLE
Not working with NetLogo 6.1.0

### ISSUE THREAD

**Issue by tfrench** [quaquel/pyNetLogo#24]
NetLogo 6.1.0 has just been released. I'm unable to get pyNetLogo working with 6.1.0. There isn't a documented change to the API. Thoughts? Thanks.

Error:
```
Traceback (most recent call last):
  File "/Users/thomasfrench/miniconda3/envs/pyNetLogo/lib/python3.6/site-packages/pyNetLogo/core.py", line 283, in load_model
    self.link.loadModel(path)
jpype._jexception.NoSuchMethodErrorPyRaisable: java.lang.NoSuchMethodError: org.nlogo.workspace.Controllable.open(Ljava/lang/String;)V

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model.py", line 22, in simulation
    netlogo.load_model(MODEL_FILENAME)
  File "/Users/thomasfrench/miniconda3/envs/pyNetLogo/lib/python3.6/site-packages/pyNetLogo/core.py", line 285, in load_model
    raise NetLogoException(ex.message())
pyNetLogo.core.NetLogoException: org.nlogo.workspace.Controllable.open(Ljava/lang/String;)V
```

**Comment by quaquel** [comment]
you are absolutely right. For some reason 6.1 does not work at present. I hope to look at it over the summer, after teaching finishes.

Too my knowledge there is no change in the underlying api, but it might be that the directory structure has changed (happened also from 5.3 to 5.4)

**Comment by quaquel** [comment]
it seems that there is a change in the underlying java code of netlogo. The open method used to take only a string, for 6.1 it requires a string and a boolean. This means that I need to maintain 3 versions of the java code: for 5.3.x, for 6.0.x, and for 6.1.x. Expect a fix on pypi somewhere later this week. I have a clunky hack on my machine working which needs more testing.
