### ISSUE TITLE
PyNetLogo on Linux cluster - NameError when running the pd.DataFrame 

### ISSUE THREAD

**Issue by m-vonessen** [quaquel/pyNetLogo#48]
Hello everyone! 

This is my first post here so I hope it's the right place to ask my question - please let me know if not :-)

I try to use PyNetLogo to run a global sensitivity analysis on a computer cluster that runs on Linux centos. I am following the PyNetLogo documentation for the Sobol sensitivity analysis pretty closely but unfortunately keep encountering an error when trying to run this line: `results = pd.DataFrame(lview.map_sync(simulation, param_values)) `: 

`NameError: name 'netlogo' is not defined` (see full error message below and attached).

I designed the model in NetLogo 6.2.0, but use a 6.0.4. version on the cluster since the 6.2.0 version gave me problems. I tried using PyNetLogo 0.3, 0.4.1 and 0.4.2, but unfortunately the error persists. Java version is 11.0.11. 
I'm also working with the cluster computer service team on this issue, but they are running out of ideas, which is why I'm posting here :) 

Any tips and suggestions are highly recommended - thanks a lot in advance 

All the best, 
Marius

```
0:apply]: ---------------------------------------------------------------------------NameError Traceback (most recent call last)<string> in <module> ~/.local/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py in <lambda>(f, *sequences) 141 142 if sys.version_info[0] >= 3: --> 143 _map = lambda f, *sequences: list(map(f, *sequences)) 144 else: 145 _map = map <ipython-input-13-647b15be93cd> in simulation(experiment) NameError: name 'netlogo' is not defined
[1:apply]: ---------------------------------------------------------------------------NameError Traceback (most recent call last)<string> in <module> ~/.local/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py in <lambda>(f, *sequences) 141 142 if sys.version_info[0] >= 3: --> 143 _map = lambda f, *sequences: list(map(f, *sequences)) 144 else: 145 _map = map <ipython-input-13-647b15be93cd> in simulation(experiment) NameError: name 'netlogo' is not defined
[2:apply]: ---------------------------------------------------------------------------NameError Traceback (most recent call last)<string> in <module> ~/.local/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py in <lambda>(f, *sequences) 141 142 if sys.version_info[0] >= 3: --> 143 _map = lambda f, *sequences: list(map(f, *sequences)) 144 else: 145 _map = map <ipython-input-13-647b15be93cd> in simulation(experiment) NameError: name 'netlogo' is not defined
[3:apply]: ---------------------------------------------------------------------------NameError Traceback (most recent call last)<string> in <module> ~/.local/lib/python3.6/site-packages/ipyparallel/client/remotefunction.py in <lambda>(f, *sequences) 141 142 if sys.version_info[0] >= 3: --> 143 _map = lambda f, *sequences: list(map(f, *sequences)) 144 else: 145 _map = map <ipython-input-13-647b15be93cd> in simulation(experiment) NameError: name 'netlogo' is not defined ... 60 more exceptions ... 
```

![Capture](https://user-images.githubusercontent.com/90417548/132749822-9e36676b-2960-4ad1-9950-fbcf0978bc11.PNG)

**Comment by quaquel** [comment]
The problem most likely is that pynetlogo does not know where netlogo is installed. On both Mac and Windows, it can make an educated guess, but not on linux. You should be able to solve this by passing the netlogo_home, netlogo_verion and most likely also jvm_home kwargs when instantiating NetLogoLink.

**Comment by flaanza** [comment]
Hi, thanks for the quick reply. This is how I instantiate the NetLogoLink:
`netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home='/home/users/vonessen/NetLogo 6.0.4', netlogo_version='6.0')`

So you would recommend also passing the jvm_home location?

Cheers, 
Marius

**Comment by m-vonessen** [comment]
Hi, thanks for the quick reply! 

This is how I instantiate the NetLogoLink:
netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home='/home/users/vonessen/NetLogo 6.0.4', netlogo_version='6.0')

Would you recommend that I also pass the jvm_home location then?

Cheers,
Marius

**Comment by quaquel** [comment]
Most likely yes, and the name jvm_home is a misnomer that still needs addressing. It is the path the the ivm executable itself that you need to pass.

The underlying issue here is jpype. If ```jpype.getDefaultJVMpath()``` returns null, then you need to specify the jvm_path yourself.

**Comment by m-vonessen** [comment]
I see, thank you for the explanation! 

So, using jpype.getClassPath() and jpype.getDefaultJVMPath() returned this path: 
'/share/software/user/open/java/11.0.11/lib/server/libjvm.so' 

I then inserted the path into the NetLogoLink like so:
`netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home='/home/users/vonessen/NetLogo 6.0.4', netlogo_version='6', jvm_home='/share/software/user/open/java/11.0.11/lib/server/libjvm.so')`

Unfortunately, the error persists. Did I miss something or got it wrong? Could it have to do with the jvm being located on a different directory than my NetLogo installation (NetLogo is on my personal directory on the cluster, but Java is not)?

Thanks again for the help! 
Marius

**Comment by quaquel** [comment]
does the code work if you run it sequentially, so not in parallel?

I would like to see the full stack trace.

**Comment by m-vonessen** [comment]
Thanks for sticking with me on this! 

I have run this script successfully on my local machine (with adaptation for file paths, etc.), using multiple cores launched with ipcluster. I have not tried to run in sequentially, though - neither on my local computer nor on the cluster. I'm also not sure how I would do this, but happy to attempt it if that would help resolve the issue. 

I'm afraid I'm not 100% sure what a full stack trace is or how to obtain it from Jupyter Notebook - is it the entire script + error messages? Definitely happy to share it once I know how to get it :) 

Cheers, 
Marius

**Comment by quaquel** [comment]
For running sequentially, you can follow example 1 on read the docs. I would start with trying that on the cluster. It seems plausible that your problems are related to the cluster and aligning the code with the cluster configuration. So next to testing pynetlogo sequentially, have you tested ipyparallel itself on the cluster with any of their examples?

**Comment by m-vonessen** [comment]
Got it - thanks, Jan!
I tried Example 1 in two ways (see below). Full transparency: I think some of these error messages are probably not relevant and/or could be fixed on my end easily, I included them anyways just in case it might hint at some underlying issues.

**1)** on a command line using SecureCRT and a conda environment. We followed this [PyNetLogo tutorial](https://medium.com/geekculture/pynetlogo-tutorial-ea3146188561) and it worked well. We weren't able to test ipyparallel that way, yet, because we thought it needs to be executed from a Jupyter Notebook, not the command line, and we need to set that up first.

**2)** On the Jupyter Notebook (Cluster computer GUI) where I also run my full script, I can load all the imports, instantiate NetLogo, load the model, and run some simple commands `(netlogo.command('repeat 100 [go]')`), using NetLogo version 6.0.4.

**2a)**
I cannot successfully run `netlogo.repeat_report(['count wolves'], 100, go='go')`, it gives me the error message: 
`TypeError: 'NetLogoLinkV6.NLResult' object is not iterable` (see full error code below).

**2b)** When trying to run 
```
agent_xy = pd.read_excel('/home/users/vonessen/xy_DataFrame.xlsx')
agent_xy[['who','xcor','ycor']].head(5)
```
from the example, I get this error message: 
`ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`
When I pip3 install xlrd, though, it tells me that it's already installed. 

**2c)** When I instantiate NetLogo with version 6.2.0, like this: 
`netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home='/home/users/vonessen/NetLogo-6.2.0', netlogo_version='6', jvm_home='/share/software/user/open/java/11.0.11/lib/server/libjvm.so')`
I get the following error when trying to load the Wolf Sheep Predation model: 
`AttributeError: module 'jpype' has no attribute 'JavaException'`

As a next step, we will try to run the Notebook and ipyparallel on the command line. If that works, that'd be great, but I'd prefer to use the GUI and the Jupyter Notebook there because I'm more familiar with creating figures etc this way. 

If you have any suggestions on what to try out, I'd really appreciate it! 

Cheers, 
Marius

FULL ERROR MESSAGES
2a) When running: `netlogo.repeat_report(['count wolves'], 100, go='go')`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in _cast_results(self, results)
    671         try:
--> 672             converted_results = type_convert(results)
    673         except:

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in type_convert(results)
    684 
--> 685     java_dtype = results.type
    686 

AttributeError: 'NetLogoLinkV6.NLResult' object has no attribute 'type'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-7-1534d0f6bebe> in <module>()
----> 1 netlogo.repeat_report(['count wolves'], 100, go='go')

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in repeat_report(self, netlogo_reporter, reps, go)
    514             raise NetLogoException("Unknown datatype")
    515 
--> 516         tick = self._cast_results(self.link.report('ticks'))
    517         results_df = pd.DataFrame(columns=cols,
    518                                   index=np.arange(tick, tick+reps))

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in _cast_results(self, results)
    673         except:
    674             converted_results=[]
--> 675             for i in results:
    676                 converted_results.append(type_convert(i))
    677 

TypeError: 'NetLogoLinkV6.NLResult' object is not iterable

2c)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/_jpype.cpython-36m-x86_64-linux-gnu.so in NetLogoLinkV6.NetLogoLink.loadModel()

Exception: Java Exception

The above exception was the direct cause of the following exception:

java.lang.NoSuchMethodError               Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in load_model(self, path)
    282         try:
--> 283             self.link.loadModel(path)
    284         except jpype.JavaException as ex:

java.lang.NoSuchMethodError: java.lang.NoSuchMethodError: org.nlogo.workspace.Controllable.open(Ljava/lang/String;)V

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-db79b3116ea3> in <module>()
----> 1 netlogo.load_model('/home/users/vonessen/Wolf-Sheep-Predation.nlogo')

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in load_model(self, path)
    282         try:
    283             self.link.loadModel(path)
--> 284         except jpype.JavaException as ex:
    285             raise NetLogoException(ex.message())
    286 

AttributeError: module 'jpype' has no attribute 'JavaException'

**Comment by quaquel** [comment]
1) Can you repeat the tutorial within a notebook?
2) that sounds hopeful
2a) this sounds like some kind of bug. I will have to test on my end. I recall seeing this error before so it might have been fixed on master. I just am not sure at this point
2b) check the version of xlrd. But this is an issue with pandas and your cluster setup. 
2c)Again, I will have to check this on my end. What version of jpype do you have installed?

**Comment by m-vonessen** [comment]
1) When repeating the tutorial in a _Notebook launched from the GUI_ of the cluster computer I run into the errors described above:
- PyNetLogo documentation --> Example 1 --> NetLogo 6.0.4. --> line [2] defining agent_zy: 
`ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.`
- PyNetLogo documentation --> Example 1 --> NetLogo 6.2.0 --> line [1] loading the model: 
`AttributeError: module 'jpype' has no attribute 'JavaException'`
- Medium Tutorial --> NetLogo 6.04. --> Get Data from Netlogo simulation --> defining x and y (x = netlogo.report('map [s -> [xcor] of s] sort sheep') and y = netlogo.report('map [s -> [ycor] of s] sort sheep')):
`AttributeError: module 'jpype' has no attribute 'JavaException'`
- Medium Tutorial --> Repeat the model simulation --> netlogo.repeat_report(['count wolves'], 100, go='go'):
`TypeError: 'NetLogoLinkV6.NLResult' object is not iterable`

I have not been able to test these tutorials on a _Notebook launched from the command line_. The cluster computer support team thinks that it might perform differently then (apparently they've had some issues with the GUI in the past in other cases). I hope to meet with the support later today to launch the Notebook from the command line, will report back.

I can run the commands above without errors on the command line (both tutorials). Interestingly, in the command line I instantiate NetLogo like this:
`netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home='/home/users/vonessen/NetLogo-6.2.0', netlogo_version='6.1', jvm_home='/share/software/user/open/java/11.0.11/lib/server/libjvm.so')`
So with NetLogo 6.2.0., but version = 6.1. Not sure if that matters, just wanted to share it :)

Regarding 2b) Versions: xlrd 2.0.1, pandas 1.2.4
Regarding 2c) Versions: Jpype1 1.2.1, pyNetLogo 0.4.2

I hope this helps and again thanks for your support - I really appreciate it! 
/marius

**Comment by quaquel** [comment]
I find it hard to make sense of this. My hunch at the moment is that in the GUI you are using different versions of libraries than on the command line. Let me explain
* the `AttributeError: module 'jpype' has no attribute 'JavaException'` makes no sense for pyNetLogo 0.4.2 because JavaException appears nowhere in the code. It was used in older versions (pre jpype 1.x). 
* The fact that the code works with 6.2, but version set to 6.1. The Java side of pyNetLogo is identical for 6.1 and 6.2 (but different for 6.0, and 5.x). So there is a dict for mapping netlogo versions to which java jar to use. This mapping actually maps 6.2 to the 6.1 jar. 

You can check this yourself. Any python library should store the version number in the __version__ tag, so do

```python
import pynetlogo

print(pynetlogo.__version__)

```

in both the gui and the command line and see what you get. You might try the same for pandas and xlrd.

**Comment by m-vonessen** [comment]
I think you're hunch might be correct. When printing the pyNetLogo version on the Notebook, it gives me version 0.3, but when I pip list it on the cluster node, it says 0.4.2. So there must be a 0.3 version somewhere that the Notenbook scrapes. 
It's been tricky to run the Notebook consistently from the command line, but once we ironed that out we will try to remove the 0.3 version (or direct the Notebook to the right version) and see what that does. 
I will report. 
Thanks!

**Comment by m-vonessen** [comment]
I might have found the error (I was able to run the script successfully twice). I went back to the documentation, my Cluster script and my local script and went through the lines one by one, making changes here and there to make them match up, and at some point I was able to run the complete script! 
I then went back and commented out things I didn't think were needed and narrowed it down to this change:
PREVIOUSLY
```
%px

import os
cwd = os.getcwd()
os.chdir(cwd)

import pyNetLogo
import pandas as pd
```
CHANGED TO:
```
%%px

import os
os.chdir(cwd)

import pyNetLogo
import pandas as pd
```

I'm still playing around with the script to make sure I can replicate everything, but it's looking promising so far. 
Another thing I noticed is that between the Notebook, my local computer, and the cluster node things are quite finicky, i.e., you really need to pay attention to the order in which you carry out the steps, tunneling through the right ports, etc. 

Thanks so much for your help, Jan, I really appreciate it. I will keep you posted should something come up.

Cheers, 
Marius
